# Generated by Django 5.0.3 on 2024-03-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('T-Shirt'), ('Jacket'), ('Shoes');
        """, """DELETE FROM store_collection WHERE title IN ('T-Shirt', 'Jacket', 'Shoes');"""),
    ]
